// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Midioteca.Data;

#nullable disable

namespace Midioteca.Migrations
{
    [DbContext(typeof(MidiotecaDbContext))]
    [Migration("20250708230105_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Midioteca.Models.ConsumoMidia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataFinalizacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MidiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Nota")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MidiaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ConsumoMidia", (string)null);
                });

            modelBuilder.Entity("Midioteca.Models.Genero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Midioteca.Models.Midia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid>("GeneroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GeneroId");

                    b.ToTable("Midias", (string)null);

                    b.HasDiscriminator().HasValue("Midia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Midioteca.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Resenha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConsumoMidiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsumoMidiaId");

                    b.ToTable("Resenhas");
                });

            modelBuilder.Entity("Midioteca.Models.Filme", b =>
                {
                    b.HasBaseType("Midioteca.Models.Midia");

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("int");

                    b.Property<string>("CapaPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diretor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Duracao")
                        .HasColumnType("int");

                    b.ToTable("Midias", t =>
                        {
                            t.Property("CapaPath")
                                .HasColumnName("Filme_CapaPath");
                        });

                    b.HasDiscriminator().HasValue("Filme");
                });

            modelBuilder.Entity("Midioteca.Models.Livro", b =>
                {
                    b.HasBaseType("Midioteca.Models.Midia");

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapaPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Paginas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Livro");
                });

            modelBuilder.Entity("Midioteca.Models.ConsumoMidia", b =>
                {
                    b.HasOne("Midioteca.Models.Midia", "Midia")
                        .WithMany()
                        .HasForeignKey("MidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Midioteca.Models.Usuario", "Usuario")
                        .WithMany("ConsumosMidia")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Midia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Midioteca.Models.Midia", b =>
                {
                    b.HasOne("Midioteca.Models.Genero", "Genero")
                        .WithMany("Midias")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Resenha", b =>
                {
                    b.HasOne("Midioteca.Models.ConsumoMidia", "ConsumoMidia")
                        .WithMany("Resenhas")
                        .HasForeignKey("ConsumoMidiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumoMidia");
                });

            modelBuilder.Entity("Midioteca.Models.ConsumoMidia", b =>
                {
                    b.Navigation("Resenhas");
                });

            modelBuilder.Entity("Midioteca.Models.Genero", b =>
                {
                    b.Navigation("Midias");
                });

            modelBuilder.Entity("Midioteca.Models.Usuario", b =>
                {
                    b.Navigation("ConsumosMidia");
                });
#pragma warning restore 612, 618
        }
    }
}
